### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by sja** [destinationstransfers/passkit#2]
Hi!

I'm not sure, thats because I don't create a PR, but `require("@destinationstransfers/passkit").createTemplate` is not a function. I did the following:

```
const {Template, Pass} = require("@destinationstransfers/passkit");
const template = new Template("eventTicket", {...
```

That seems to work, but it stops on loading the images. I did a `template.images.loadFromDirectory("images");` and the relative path contains e.g. a `icon.png` and a `thumbnail.png` but I get the following error:

```
pass.loadImagesFrom("images");
     ^

TypeError: pass.loadImagesFrom is not a function
    at Object.<anonymous> (/Users/sja/dev/testpass/index.js:20:6)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
```

**Comment by tinovyatkin** [comment]
Thank you! Still lot of cleanup from old project pending, will update it today.
Basically as everything were refactored into real classes init construction now is:
```js
const { Template } = require('@destinationstransfers/passkit');
const template = new Template(...); // or Template.load(...)
...
const Pass = template.createPass(...)
```
