### ISSUE TITLE
Uncaught Error: This file no longer open for writing

### ISSUE THREAD

**Issue by onlyamir007** [destinationstransfers/passkit#35]
When im running pass_test.js im getting this error please help me out what im doing wrong?

` mocha pass_test.js

  Pass
    from template
      √ should copy template fields
      √ should start with no images
      √ should create a structure based on style
    without serial number
      √ should not be valid
    without organization name
      √ should not be valid
    without description
      √ should not be valid
    without icon.png
      √ should not be valid
    without logo.png
undefined
      √ should not be valid
    generated
      1) "before all" hook

  8 passing (49ms)
  1 failing

  1) Pass
       generated
         "before all" hook:
     Uncaught Error: This file no longer open for writing
      at File.write (C:\Users\mrima\node-work\passkit\lib\zip.js:278:11)
      at SHAWriteStream.write (C:\Users\mrima\node-work\passkit\lib\pass.js:409:15)
      at ReadStream.ondata (_stream_readable.js:555:20)
      at readableAddChunk (_stream_readable.js:176:18)
      at ReadStream.Readable.push (_stream_readable.js:134:10)
      at onread (fs.js:2018:12)
      at FSReqWrap.wrapper [as oncomplete] (fs.js:682:17)`

**Comment by tinovyatkin** [comment]
This project doesn't use mocha for tests, so, I'm not sure what you are trying to test at "before all" hook
