### ISSUE TITLE
Invalid regexp

### ISSUE THREAD

**Issue by nickasd** [destinationstransfers/passkit#71]
With the newest version, as soon as I include `require('@destinationstransfers/passkit')` I get the error
```
node_modules/@destinationstransfers/passkit/dist/lib/images.js:13
exports.IMAGE_FILENAME_REGEX = new RegExp(`^(?<imageType>${Object.keys(constants_1.IMAGES).join('|')}+)(@(?<density>[23]x))?.png$`);
                               ^

SyntaxError: Invalid regular expression: /^(?<imageType>icon|logo|background|footer|strip|thumbnail+)(@(?<density>[23]x))?.png$/: Invalid group
    at new RegExp (<anonymous>)
    at Object.<anonymous> (node_modules/@destinationstransfers/passkit/dist/lib/images.js:13:32)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (node_modules/@destinationstransfers/passkit/dist/lib/base-pass.js:5:18)
```

**Comment by nickasd** [comment]
After updating to NodeJS 10.15.3, the problem is solved.

**Comment by tinovyatkin** [comment]
@nickasd  Yes, it's named capture groups that requiring never Node.
